// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFca_J4mvUVcbiN-x9w8nZOxEhmRlRF9w',
    appId: '1:631478292342:web:53879c2bee8edbd930f457',
    messagingSenderId: '631478292342',
    projectId: 'bmi-tracker-f1adb',
    authDomain: 'bmi-tracker-f1adb.firebaseapp.com',
    storageBucket: 'bmi-tracker-f1adb.firebasestorage.app',
    measurementId: 'G-F9P3RNN2WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevfmFugC_tlHEikxYZhmdym2KQfXYn0U',
    appId: '1:631478292342:android:fa4bf0a4bff496be30f457',
    messagingSenderId: '631478292342',
    projectId: 'bmi-tracker-f1adb',
    storageBucket: 'bmi-tracker-f1adb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TZi6jeSgYljMz-7IDhB6riz9WR9nEKE',
    appId: '1:631478292342:ios:d0d85698b8eebef230f457',
    messagingSenderId: '631478292342',
    projectId: 'bmi-tracker-f1adb',
    storageBucket: 'bmi-tracker-f1adb.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3TZi6jeSgYljMz-7IDhB6riz9WR9nEKE',
    appId: '1:631478292342:ios:d0d85698b8eebef230f457',
    messagingSenderId: '631478292342',
    projectId: 'bmi-tracker-f1adb',
    storageBucket: 'bmi-tracker-f1adb.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFca_J4mvUVcbiN-x9w8nZOxEhmRlRF9w',
    appId: '1:631478292342:web:02c310ea3fca96b130f457',
    messagingSenderId: '631478292342',
    projectId: 'bmi-tracker-f1adb',
    authDomain: 'bmi-tracker-f1adb.firebaseapp.com',
    storageBucket: 'bmi-tracker-f1adb.firebasestorage.app',
    measurementId: 'G-3V4T0QLXQ0',
  );
}
